site_name: Bhreia
copyright: Copyright &copy; 2021 Eddy Luten
repo_url: https://github.com/EddyLuten/bhreia.com
repo_name: EddyLuten/bhreia.com
plugins:
  - awesome-pages
  - git-revision-date
  - search:
      lang: en
  - snippet:
        base_path: docs
extra:
  analytics:
    provider: google
    property: G-4Y6GVT3ZWF
markdown_extensions:
  - pymdownx.emoji
  - attr_list
  - admonition
  - mdx_truly_sane_lists
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - assets/stylesheets/bhreia.css
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/dice-d20
    admonition:
      info: octicons/info-16
  palette:
    scheme: default
    primary: blue
    accent: orange
  features:
    # - navigation.expand
    - navigation.sections
    # - navigation.indexes
    - navigation.top
    # - toc.integrate
    - search.suggest
